### ISSUE TITLE
Career Timeline

### ISSUE THREAD

**Issue by GlenCodez** [GlenCodez/glenned.com#3]
## Background
- Base design off [Folium Template](https://demo2.joomshaper.com/2019/folium/index.php/home/web-developer)

## Tasks
- [ ] Write a heading statement
- [ ] Organize and write descriptions for each timeline item
- [ ] Static styled timeline list
- [ ] Animate timeline list
